### ISSUE TITLE
What url i should type in browser if i run it using docker?

### ISSUE THREAD

**Issue by pavanyogi** [danactive/history#398]
Yes, I am using the latest version.
### What is the *current* behaviour?
I could not find the local URL, which I need to paste in the browser to see the app in the actions.

### What is the *expected* behaviour?
There should be mention of the local app URL if it is run using the docker.

#### Please mention your Node.js, yarn, operating system, and `history` versions.
Ubuntu-16.04, node v10.19.0

**Comment by danactive** [comment]
I pushed a new version with documentation and I lessened the Dropbox requirement

Point your browser to
http://localhost:3000

You should see something like this in the CLI
ui_1   | -----------------------------------
ui_1   | Localhost: http://localhost:3000
ui_1   |       LAN: http://172.18.0.3:3000
ui_1   | -----------------------------------
