### ISSUE TITLE
View Album - Nearby photos from Instagram community

### ISSUE THREAD

**Issue by danactive** [danactive/history#56]
As a user, I want nearby photos available for viewing when viewed photo is mappable.

Story Acceptance Criteria:
* Definition: *Album media* is either a photo or video in the Sample album of the Demo gallery
* When *album media* is viewed in lightbox and has geocode then display hyperlink
* Clicking on hyperlink will display <50 crowd sourced photos within 1 km proximity of the *album media*
* Format the *album media* using this [jQuery plugin to fully justify](https://miromannino.github.io/Justified-Gallery/)
* Crowd sourced photos will close (and reset ready to open again) when next or previous *album media* is viewed using arrows on the keyboard or mouse click

**Comment by drewhan90** [comment]
Please assign this to me.

**Comment by danactive** [comment]
No longer using jQuery (React.js is the campaign), so closing issue
